#/*************************************************
#Arxeio ylopoihshs	: Makefile
#Syggrafeas			: A. Kalamakis
#Skopos				: make file for ask1
#Revision 			: Antonis Kalamakis sdi1800056
#**************************************************/

run: ch6_QArray.c ch6_Simulation.c TStoixeiouOuras.c ch6_Controller.c
	gcc -o run ch6_QArray.c ch6_Simulation.c TStoixeiouOuras.c ch6_Controller.c
